name: Publish NuGet Package

on:
  push:
    branches:
      - master # Trigger on pushes to the master branch
  create:
    tags: # Trigger when a tag is added to the repository
      - '*'
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build-and-publish:
    name: Build and Publish to NuGet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Determine package version
        id: version
        run: |
          if [ "${{ github.event_name }}" == "create" ]; then
            echo "::set-output name=version::${{ github.ref_name }}"
          else
            latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
            echo "::set-output name=version::${latest_tag}-preview.$(date +%s)"
          fi

      - name: Pack the NuGet package
        run: |
          dotnet pack --configuration Release --no-build --output ./nupkg /p:Version=${{ steps.version.outputs.version }}

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push ./nupkg/*.nupkg \
            --source https://api.nuget.org/v3/index.json \
            --api-key $NUGET_API_KEY
